version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: online-retail-etl
    private_key_id: cb77429050621016d94c1882bee2fc9d8652cd35
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCa5BQfD7kFkctv\nbvMRupcpI/fL+QPbexH6460NdvGt53AnZRwT3q08aScQCC/03H3OPU2wW6pwHDjC\n8VUgsT1WJ3AORT3Y0dKv/KFuM3GHiHpdQablTfejA1UEOGdxmVE0JEmFFzQVRss5\nMnrXHg5wCOou0DlfvXEkLqzFKzyoC2wY41BKRARtpHl+QYMtPQNKEQKlBPivwz8m\njDLEiUDZnki1bdxPSaztv+AR5huhc3Ye7r64/gcUh4xd4vjuPX2L3qbTgZNec5fk\nc2E9w2KGf3Lgb3wdzfNACWgvmzlBgzYOpkY7tR6Y5H8yk7NkuEfylrsLgrR5iL5S\nATBqCXPxAgMBAAECggEAEeoT/TE0dzVQ/A0PKjNkaQ7WycW96VhLQLMtSFfD1Vcl\nqLrII/Cu5OQtD0zBHi8T0mMS/ZUmifOrqXlf3Ql+1Hx4eIAP6og/F9luYthqlrBF\nZcySdOY/AGDB6Bxtc202AAO76Juhy52t4spIvKFmblULn9k3r4/xumt3ElFhQTat\n3zc5g23UR+s0a2hjmXJ1igi0f0clz+Gw465kircaO4x9sFSalkAQyu0LJ2T4hKK3\nkrdCAa3TNXzPJhL8WGgEi5EGMAoi+Ij8rfwMoZ8gUMGMq6soM8tg21OSmjOYL60A\nuW4+/jFWtFNwbC8ktmE44Xv0SgsQc1N/1O6iZe++WQKBgQDQ3O2h5Ivd32ILHAan\n85vH3V7jx0c6dlK6LFdsnZDOU+dFXaXijs/Ag7zHSLDoqcIvv9pN6I2b5Z1kHSbp\nD+FMP/xrmH9t8X/mtvOVFtiBJXVtqsYEcqJBqOmkAqyE63zXKrBCyoRzufuoTcl6\n3Hifg+BMJubDacH/hbVP2lUtiQKBgQC92Ok3Gognx7I/nsv27ePz0grQNk/YRXRT\no22LUbGJgSB1ghB3DpgBg7TqpRMBmGelQJVvkil49OHrmW6tNxejTyYjKiT2Vcnx\n4WuqGjfmKo3cysYzVWIFnuT4A1Vjd/TwOqnEjsTSwHmBMXIHVxJ9U3vmAARmRtmm\nJDBxHDKhKQKBgAwBVutiTqPPLjyDPOK0fvTLBaREFRUILhMjb1b/643ghr+W9W0D\nVm+zYst1oy2MbGwANBUcU99tIFHb1xu4XPPcDa9FkbWJFxf01iVwrbsmowxNr5ob\n2LW7dsqFmNL/Eirv+jesmlZoj02KQxV7zLcmhmL6LXN4Bb2hOt2/J/w5AoGBALnN\nqmqY1/r+8hBcDUluCDSgNJ8VGM4VI8Wb5GF/Id/u9eKr2gt7x/9rdMxVpSVhkMbm\nT5rzlQ1hth7MesqiacsWcr/lxmklC1FlCudfY6grq84U0yh4f0f6/CNTt+VzCNF4\nyKCsDiwp3oE38F8Is/rekxtGlwe2fduh/ZsmOtMJAoGAbGv2QwxzsEYoFChoV6mV\nh+lChumaWsKc3niMmy7L3e+zSvSoEbvWnO5EuEIJ058eHGMPW+7iY3mG19yY3CUm\nP5hP0gqs4qSPrWR8O7to/vlE6vmWQAum/W5Vhkionc1FelHQxMnyPqCE7uRwr3dA\ninY4wUdWJ86LS3wt2ltthUQ=\n-----END PRIVATE KEY-----\n"
    client_email: bigquery-admin@online-retail-etl.iam.gserviceaccount.com
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/bigquery-admin@online-retail-etl.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/mage_data/secrets/key.json"
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
